name: Messages customs
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  messages:
    name: Modifier les messages
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger les fichiers
        uses: wei/wget@v1
        with:
          args: -O messages.properties https://raw.githubusercontent.com/SpigotMC/BungeeCord/master/proxy/src/main/resources/messages.properties
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Lancer le script
        run: node script.js
      - name: Pousser les modifs
        run: |
          git init
          git remote add origin https://github.com/EarthNetwork/proxy-messages
          git add messages.properties
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Mise à jpir"
          git push
